### ISSUE TITLE
Невозможность гарантировать полный набор данных

### ISSUE THREAD

**Issue by EnergoStalin** [EnergoStalin/pfg-parser#1]
# Минимальный возможный набор данных на выборке в 1233 последние декларации

```json
[
  "idDeclaration",
  "idDeclScheme",
  "idObjectDeclType",
  "idDeclType",
  "idStatus",
  "number",
  "declRegDate",
  "noSanction",
  "lastUpdate",
  "applicant.idLegalSubject",
  "applicant.idApplicantType",
  "applicant.idLegalSubjectType",
  "applicant.ogrn",
  "applicant.ogrnAssignDate",
  "applicant.inn",
  "applicant.regDate",
  "applicant.regOrganName",
  "applicant.transnational",
  "applicantFilials",
  "manufacturer.idLegalSubject",
  "manufacturer.idLegalSubjectType",
  "manufacturer.transnational",
  "product.idProduct",
  "product.idProductOrigin",
  "product.fullName",
  "experts",
  "documents.productionControlResults",
  "documents.reportsOnTypeApprovalUnderUNRegulation",
  "documents.complianceStandards",
  "isSrd",
  "idStatusTestingLabs"
]
```

**Comment by EnergoStalin** [comment]
В связи с этим предлагаю отказаться от табличного формата и хранить всё в json
json cli уже готова при чем как для фильтров деклараций так и для самих деклараций

**Comment by ArmenKhachikyan** [comment]
json это, в общем, нормально. Учитывая объем данных оно даже, наверное, и лучше.

**Comment by EnergoStalin** [comment]
> # Минимальный возможный набор данных на выборке в 1233 последние декларации
> ```json
> [
>   "idDeclaration",
>   "idDeclScheme",
>   "idObjectDeclType",
>   "idDeclType",
>   "idStatus",
>   "number",
>   "declRegDate",
>   "noSanction",
>   "lastUpdate",
>   "applicant.idLegalSubject",
>   "applicant.idApplicantType",
>   "applicant.idLegalSubjectType",
>   "applicant.ogrn",
>   "applicant.ogrnAssignDate",
>   "applicant.inn",
>   "applicant.regDate",
>   "applicant.regOrganName",
>   "applicant.transnational",
>   "applicantFilials",
>   "manufacturer.idLegalSubject",
>   "manufacturer.idLegalSubjectType",
>   "manufacturer.transnational",
>   "product.idProduct",
>   "product.idProductOrigin",
>   "product.fullName",
>   "experts",
>   "documents.productionControlResults",
>   "documents.reportsOnTypeApprovalUnderUNRegulation",
>   "documents.complianceStandards",
>   "isSrd",
>   "idStatusTestingLabs"
> ]
> ```

Что то я намудрил @ArmenKhachikyan тут нету контактов хотя они везде есть в поле applicant.contacts
Так что можно уже брать и использовать

**Comment by EnergoStalin** [comment]
@ArmenKhachikyan А нет не намудрил пока тестил пример наткнулся на такую [декларацию](https://pub.fsa.gov.ru/rds/declaration/view/17346771/common) контактов там вообще нету ни в апишке не в интерфейсе

И таких много к примеру ещё несколько
[17346788](https://pub.fsa.gov.ru/rds/declaration/view/17346788/common)
[17346792](https://pub.fsa.gov.ru/rds/declaration/view/17346792/common)

**Comment by ArmenKhachikyan** [comment]
Госсервисы - вечная куча мусора.

**Comment by EnergoStalin** [comment]
Не так уж и плохо на самом деле. Хорошо что хоть не html рендеринг. Это когда апи нету и оно вшито в страницу. Тогла парсинга html не избежать.
